// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2TBPrzU77CttdDpaYkVHd0nz7pEkFgQI',
    appId: '1:115527723160:web:0f3dcc590a1f10acf1c8ed',
    messagingSenderId: '115527723160',
    projectId: 'trippo-dece1',
    authDomain: 'trippo-dece1.firebaseapp.com',
    storageBucket: 'trippo-dece1.firebasestorage.app',
    measurementId: 'G-89ELT44FVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3l9o_THZk-SHXipb1ZxCa2lyVTyR3UhU',
    appId: '1:115527723160:android:3040a4bb277fdaa5f1c8ed',
    messagingSenderId: '115527723160',
    projectId: 'trippo-dece1',
    storageBucket: 'trippo-dece1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbDKuxK3jNsAxV4s3cY6PMmX440_7JwQM',
    appId: '1:115527723160:ios:bcab8d2c8863685df1c8ed',
    messagingSenderId: '115527723160',
    projectId: 'trippo-dece1',
    storageBucket: 'trippo-dece1.firebasestorage.app',
    iosBundleId: 'com.example.travelbudgetPro',
  );
}
